version: '3'

services:
  llm-privacy-layer-test:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./test_reports:/app/test_reports
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
      - TEST_RESULTS_FILE=/app/test_reports/test_results.md
    command: pytest tests/utils/test_anonymizer.py -v
